version: '2'

services:
    influxdb:
        build: influxdb
        ports:
            - "8086:8086"
    telegraf:
        build: telegraf
        links:
            - influxdb
    kapacitor:
        build: kapacitor
        ports:
            - "9092:9092"
        links:
            - influxdb
    chronograf:
        image: quay.io/influxdb/chronograf:1.2.0-beta5
        ports:
            - "8888:8888"
        links:
            - influxdb
            - kapacitor
        depends_on:
            - kapacitor
            - influxdb
            - telegraf
